# Generated by Django 2.2.13 on 2020-10-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province_code', models.CharField(max_length=5)),
                ('Province_name', models.CharField(max_length=50)),
                ('Administrative_area_code', models.CharField(max_length=50)),
                ('Single_Family_Residence', models.CharField(max_length=50)),
                ('Multi_family_housing', models.CharField(max_length=50)),
                ('Industry', models.CharField(max_length=50)),
                ('Public_service', models.CharField(max_length=50)),
                ('Other_build', models.CharField(max_length=50)),
                ('Others', models.CharField(max_length=50)),
            ],
        ),
    ]
